CREATE TABLE IF NOT EXISTS author
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS book
(
    id SERIAL PRIMARY KEY NOT NULL,
    author_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL,

    CONSTRAINT fk_book_author_id FOREIGN KEY (author_id) REFERENCES book(id)
);